apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-slight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-slight
  template:
    metadata:
      labels:
        app: wasm-slight
    spec:
      runtimeClassName: wasmtime-slight
      containers:
        - name: gh-latest-commits-demo
          image: REGISTRY_URL/gh-latest-commits-demo:latest
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: gh-latest-commits-demo-database
                key: connection-url
          command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-slight
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: wasm-slight
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wasm-slight
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wasm-slight
                port:
                  number: 80