specversion = "0.2"

[[capability]]
resource = "keyvalue.filesystem"
name = "placeholder-name"
    # This capability does not require any configs

[[capability]]
resource = "http-client"
name = "something"

[[capability]]
resource = "http"
name = "my-rest-api"
    # This capability does not require any configs

[[capability]]
resource = "sql.postgres"
name = "my-db"
    [capability.configs]
    POSTGRES_CONNECTION_URL = "${envvars.DB_URL}"